### ISSUE TITLE
Sample serving: Dependency installation during pod creation is unstable and slow

### ISSUE THREAD

**Issue by Ruminateer** [PaddleFlow/ElasticServing#35]
Current hub.baidubce.com/paddlepaddle/serving:latest doesn't work with `config/samples/elasticserving_v1_paddle.yaml` as the following command failed with the following error.
https://github.com/PaddleFlow/ElasticServing/blob/0ae1ea2b00647efcecf034b6a6f286fc2c35fa26/config/samples/elasticserving_v1_paddle.yaml#L19
```
python: can't open file '/Serving/python/examples/lac/lac_web_service.py': [Errno 2] No such file or directory
```
Image info
```
$ docker images --digests hub.baidubce.com/paddlepaddle/serving
REPOSITORY                              TAG       DIGEST                                                                    IMAGE ID       CREATED        SIZE
hub.baidubce.com/paddlepaddle/serving   latest    sha256:2e234858a85a16e18f736e7ce71720fb9ad6e86fc25610b4c11285e26ca07bbd   825a7fd941ac   4 months ago   450MB
```
<s>Need to use a tag other than `latest` in https://github.com/PaddleFlow/ElasticServing/blob/0ae1ea2b00647efcecf034b6a6f286fc2c35fa26/config/configmap/configmap.yaml#L10</s>

**Comment by Ruminateer** [comment]
After a few restarts, the pod starts to giving different logs??
[paddleservice_pod.log](https://github.com/PaddleFlow/ElasticServing/files/6334594/paddleservice_pod.log)

**Comment by Ruminateer** [comment]
So the problem seems to be `git clone` exiting with non zero code at https://github.com/PaddleFlow/ElasticServing/blob/0ae1ea2b00647efcecf034b6a6f286fc2c35fa26/config/samples/elasticserving_v1_paddle.yaml#L16

Guess I am closing this, as I cannot fix the unstable GitHub connection within this repo.

**Comment by Ruminateer** [comment]
I think we can do something about this. We can pack a new image basing on the serving image. Dependency installation is better done during `docker build` than during pod creation.

**Comment by jinminhao** [comment]
Yes, ```git clone``` is sometimes unstable. The temporary solution is to pack a new image. Of course this will lose some kind of flexibility. Maybe we can try to find out a better solution later.
